spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: password
jwt:
  secret: VGhpcy1pcy1hLWxvbmc0MDhtZXItc2VjcmV0LWtleS1jaGFuZ2UtaXQtaW4tcHJvZA==
  expiration: 86400000
